data:
  url: "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  separator: ";"
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 200
  max_depth: 6
  learning_rate: 0.05
  num_leaves: 31
  random_state: 42

mlflow:
  experiment_name: "Wine-Quality-Pipeline"
  model_name: "WineQualityClassifier"

thresholds:
  accuracy: 0.70
  f1_score: 0.68